# Regularly updates the CI.
name: Bump yamlfile
on:
  workflow_call:
    inputs:
      source-repository:
        type: string
        required: true
      source-ref:
        type: string
        required: false
        default: main
      yaml-path:
        type: string
        required: true
      file:
        type: string
        required: true
      base-branch:
        type: string
        required: false
        default: main
      cicd-labels:
        type: string
        required: false
        default: Run CICD
      pr-reviewers:
        type: string
        required: false
    secrets:
      PAT:
        required: true

defaults:
  run:
    shell: bash -x -e -u -o pipefail {0}

jobs:
  bump-file:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout ${{ inputs.source-repository }}
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.source-repository }}
          ref: ${{ inputs.source-ref }}
          path: ${{ github.run_id }}

      - name: Get latest source commit
        id: ref
        run: |
          cd ${{ github.run_id }}      
          sha=$(git rev-parse HEAD)
          repo=$(echo ${{ inputs.source-repository }} | tr '/' '-')
          echo "sha=${sha}" >> "$GITHUB_OUTPUT"
          echo "short_sha=${sha:0:7}" | tee -a "$GITHUB_OUTPUT"
          echo "date=$(date +%F)" | tee -a "$GITHUB_OUTPUT"
          echo "repo=$repo" | tee -a "$GITHUB_OUTPUT"

      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          path: ${{ github.run_id }}
          token: ${{ secrets.PAT }}
          ref: ${{ inputs.base-branch }}

      - name: Bump file
        env:
          PATH: ${{ inputs.yaml-path }}
          VALUE: ${{ steps.ref.outputs.sha }}
          FILE: ${{ inputs.file }}
        run: |
          cd ${{ github.run_id }}     

          yq 'eval(strenv(YAMLPATH)) = env(VALUE)' $FILE

      - name: Create Bump PR
        uses: peter-evans/create-pull-request@v6
        id: create-pull-request
        env:
          title: "chore(beep boop ğŸ¤–): Bump `${{ inputs.argument }}=${{ steps.ref.outputs.short_sha }}...` (${{ steps.ref.outputs.date }})"
        with:
          path: ${{ github.run_id }}
          branch: bump-ci-container--${{ steps.ref.outputs.repo }}-${{ steps.ref.outputs.date }}
          base: ${{ inputs.base-branch }}
          title: ${{ env.title }}
          token: ${{ secrets.PAT }}
          body: |
            ğŸš€ PR to bump `${{ inputs.source-repository }}` in `${{ inputs.file }}` to `${{ inputs.argument }}=${{ steps.ref.outputs.sha }}`.  

            ğŸ“ Please remember the following to-do's before merge: 
            - [ ] Verify the presubmit CI  

            ğŸ™ Please merge this PR only if the CI workflow completed successfully.
          commit-message: ${{ env.title }}
          signoff: true
          reviewers: ${{ inputs.pr-reviewers }}
          labels: "${{ inputs.cicd-labels }}"
